apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "devopsmetrics.fullname" . }}-grafana
  labels:
    {{- include "devopsmetrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      {{- include "devopsmetrics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dashboard
  template:
    metadata:
      labels:
        {{- include "devopsmetrics.labels" . | nindent 8 }}
        app.kubernetes.io/component: dashboard
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 472
        fsGroup: 472
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}:{{ .Values.grafana.tag }}
          ports:
            - containerPort: {{ .Values.grafana.service.port }}
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ template "devopsmetrics.fullname" . }}-grafana
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: {{ template "devopsmetrics.fullname" . }}-grafana

