apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "devopsmetrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
  name: {{ template "devopsmetrics.fullname" . }}-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.storage }}