{{- if .Values.ingress.enabled -}}
{{- $fullName := include "devopsmetrics.fullname" . -}}
{{- $svcPort := .Values.grafana.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-grafana
  labels:
    {{- include "devopsmetrics.labels" . | nindent 4 }}
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: daimler-acme
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    kubernetes.io/ingress.class: traefik-v2
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ template "devopsmetrics.fullname" . }}-grafana-stripprefix@kubernetescrd
spec:
  rules:
    {{- range .Values.grafana.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-grafana
                port:
                  number: {{ $svcPort  }}
          {{- end }}
    {{- end }}
{{- end }}