apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "devopsmetrics.fullname" . }}-influx
  labels:
    {{- include "devopsmetrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.influxdb.storage }}