apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "devopsmetrics.fullname" . }}-influx
  labels:
    {{- include "devopsmetrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "devopsmetrics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "devopsmetrics.labels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      volumes:
        - name: influx-storage
          persistentVolumeClaim:
            claimName: {{ template "devopsmetrics.fullname" . }}-influx
      containers:
        - name: influx
          image: {{ .Values.influxdb.image }}:{{ .Values.influxdb.tag }}
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: /var/lib/influx
              name: influx-storage
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-influx
                  key: influx-user
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-influx
                  key: influx-password
            - name: DOCKER_INFLUXDB_INIT_ORG
              valueFrom:
                secretKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-influx
                  key: influx-org
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-influx
                  key: influx-bucket
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-influx
                  key: influx-token

