apiVersion: v1
kind: Secret
metadata:
  name: influx-secret
type: Opaque
data:
  influx-user: {{ .Values.influxdb.secret.influxUser | b64enc }}
  influx-org: {{ .Values.influxdb.secret.influxOrg | b64enc }}
  influx-password: {{ .Values.influxdb.secret.influxPassword | b64enc }}
  influx-token: {{ .Values.influxdb.secret.influxToken | b64enc }}
