apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "devopsmetrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
  name: {{ template "devopsmetrics.fullname" . }}-webapp
type: Opaque
data:
  api-key: {{ .Values.webapp.apiKey | b64enc }}
  github-oauth: {{ .Values.webapp.githubOAuth | b64enc }}
  github-user: {{ .Values.webapp.githubUser | b64enc }}
