apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "devopsmetrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
  name: {{ template "devopsmetrics.fullname" . }}-webapp
spec:
  replicas: {{ .Values.webapp.replicas }}
  selector:
    matchLabels:
      {{- include "devopsmetrics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webapp
  template:
    metadata:
      labels:
        {{- include "devopsmetrics.labels" . | nindent 8 }}
        app.kubernetes.io/component: webapp
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: webapp
          image: {{ .Values.webapp.image }}:{{ .Values.webapp.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.webapp.service.port }}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-webapp
                  key: api-key
            - name: INFLUX_ORG
              valueFrom:
                secretKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-influx
                  key: influx-org
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-influx
                  key: influx-token
            - name: INFLUX_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-influx
                  key: influx-bucket
            - name: INFLUX_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-influx
                  key: influx-url
            - name: TEST_MODE
              value: "{{ .Values.webapp.testMode}}"
            - name: GITHUB_URL
              value: "{{ .Values.webapp.githubUrl}}"
            - name: GITHUB_OAUTH
              valueFrom:
                secretKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-webapp
                  key: github-oauth
            - name: GITHUB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "devopsmetrics.fullname" . }}-webapp
                  key: github-user
