apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
data:
  api-key: {{ .Values.webapp.apiKey | b64enc }}
  gh-user: {{ .Values.webapp.githubUser | b64enc }}
  gh-oauth: {{ .Values.webapp.githubOAuth | b64enc }}
