apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "devopsmetrics.fullname" . }}
  labels:
    app: webapp
spec:
  replicas: {{ .Values.webapp.replicas }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: webapp
          image: {{ .Values.webapp.image }}:{{ .Values.webapp.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: api-key
            - name: INFLUX_ORG
              valueFrom:
                secretKeyRef:
                  name: influx-secret
                  key: influx-org
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influx-secret
                  key: influx-token
            - name: INFLUX_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: influx-config
                  key: influx-bucket
            - name: INFLUX_URL
              valueFrom:
                configMapKeyRef:
                  name: influx-config
                  key: influx-url
            - name: TEST_MODE
              value: "{{ .Values.webapp.testMode}}"
            - name: GITHUB_URL
              value: "{{ .Values.webapp.githubUrl}}"
            - name: GITHUB_OAUTH
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: gh-oauth
            - name: GITHUB_USER
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: gh-user

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "devopsmetrics.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: {{ .Values.webapp.nodePort }}
