apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
data:
  api-key: {{ .Values.webapp.apiKey | b64enc }}
  gh-user: {{ .Values.webapp.gitHubUser | b64enc }}
  gh-oauth: {{ .Values.webapp.gitHubOauth | b64enc }}
  gh-url: {{ .Values.webapp.gitHubUrl | b64enc }}
