webapp:
  image: registry.app.corpintra.net/simsearch/devopsmetrics

  tag: latest
  replicas: 1
  nodePort: 30303
  
  apiKey: "your key"
  testMode: "test"

  githubUrl: "your url"
  githubOAuth: "???"
  githubUser: "???"

  service:
    port: 8080
    type: NodePort
    nodePort: 30303

  ingress:
    enabled: false
    

influxdb:
  image: registry.app.corpintra.net/dockerhub/library/influxdb
  tag: 2.3
  storage: 2Gi
  config:
    influxUrl: http://devopsmetrics-influx:8086
    influxBucket: events
  secret:
    influxUser: "???"
    influxOrg:  "???"
    influxPassword:  "???"
    influxToken:  "???"
  service:
    port: 8086
    type: NodePort
    nodePort: 30305

grafana:
  image: registry.app.corpintra.net/dockerhub/grafana/grafana-oss
  tag: 9.0.2
  
  storage: 1Gi

  service:
    port: 3000
    type: NodePort
    nodePort: 30304

  ingress:
   

networkpolicy:
  enabled: true




