webapp:
  image: registry.app.corpintra.net/simsearch/devopsmetrics

  tag: latest
  replicas: 1
  nodePort: 30303
  apiKey: #
  testMode: #

influxdb:
  image: registry.app.corpintra.net/dockerhub/library/influxdb
  tag: 2.3
  storage: 2Gi
  config:
    influxUrl: http://devopsmetrics-influx:8086
    influxBucket: events
  secret:
    influxUser: #
    influxOrg: #
    influxPassword: #
    influxToken: #

grafana:
  image: registry.app.corpintra.net/dockerhub/grafana/grafana-oss
  tag: 9.0.2
  nodePort: 30304
  storage: 1Gi
