{
 "title": "DevOpsMetrics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "AggregateInterval", "label": "Aggregation Interval", "query": "1d,7d,14d,30d" },
   { "name": "bucket", "label": "set the bucket name", "query": "${VAR_BUCKET}" }
  ]
 },
 "panels": [
  { "title": "Deployment Frequency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment Frequency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": " from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment\" and r[\"_field\"] == \"id\")\r\n  |> unique(column: \"_value\")\r\n  |> elapsed()\r\n  |> mean(column: \"elapsed\")"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: date.sub(from:${__from:date},d: ${AggregateInterval}), stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment\" and r[\"_field\"] == \"id\")\r\n  |> unique(column: \"_value\")\r\n  |> elapsed()\r\n  |> map(fn: (r) => ({_value: r[\"elapsed\"], _time: r[\"_time\"]}))\r\n  |> aggregateWindow(every: ${AggregateInterval}, fn: mean, createEmpty: false)"
    }
   ]
  },
  { "title": "Lead Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Lead Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "deploys = from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment\" and r[\"_field\"] == \"change\")\r\n\r\nchanges = from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"change\" and r[\"_field\"] == \"id\")\r\n\r\njoin(\r\n    tables: {change:changes, deploy:deploys},\r\n    on: [\"_value\"],\r\n)\r\n  |> map(fn: (r) => ({_value: uint(v: r[\"_time_deploy\"]) - uint(v: r[\"_time_change\"])}))\r\n  |> mean()\r\n"
    }
   ]
  },
  {
   "title": "Lead Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\ndeploys = from(bucket: \"${bucket}\")\r\n  |> range(start: date.sub(from:${__from:date}, d: ${AggregateInterval}), stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment\" and r[\"_field\"] == \"change\")\r\n\r\nchanges = from(bucket: \"${bucket}\")\r\n  |> range(start: date.sub(from:${__from:date}, d: ${AggregateInterval}), stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"change\" and r[\"_field\"] == \"id\")\r\n\r\njoin(\r\n    tables: {change:changes, deploy:deploys},\r\n    on: [\"_value\"],\r\n)\r\n  |> map(fn: (r) => ({_value: uint(v: r[\"_time_deploy\"]) - uint(v: r[\"_time_change\"]), _time: r[\"_time_deploy\"]}))\r\n  |> aggregateWindow(every: ${AggregateInterval}, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  { "title": "Change Fail Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Change Fail Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\r\nincident = from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"incident\")\r\n    |> count()\r\n    |> findColumn(\r\n        fn: (key) => key._field == \"id\",\r\n        column: \"_value\",\r\n    )\r\n\r\ndeployment = from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"deployment\" and r[\"_field\"] == \"id\")\r\n    |> unique(column: \"_value\")\r\n    |> count()\r\n    |> findColumn(\r\n        fn: (key) => key._field == \"id\",\r\n        column: \"_value\",\r\n    )\r\n\r\narray.from(rows: \r\n  if deployment |> length() == 1 and incident |> length() == 1 then\r\n    [{_value: float(v: incident[0]) / float(v: deployment[0]) }]\r\n  else \r\n    [{_value: float(v: 0)}] \r\n)"
    }
   ]
  },
  {
   "title": "Change Fail Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "import \"array\"\r\nimport \"date\"\r\n\r\nincident = from(bucket: \"${bucket}\")\r\n    |> range(start: date.sub(from:${__from:date}, d: ${AggregateInterval}), stop: ${__to:date})\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"incident\")\r\n    |> aggregateWindow(every: ${AggregateInterval}, fn: count)\r\n  \r\ndeployment = from(bucket: \"${bucket}\")\r\n    |> range(start: date.sub(from:${__from:date}, d: ${AggregateInterval}), stop: ${__to:date})\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"deployment\" and r[\"_field\"] == \"id\")\r\n    |> unique(column: \"_value\")\r\n    |> aggregateWindow(every: ${AggregateInterval}, fn: count)\r\n \r\njoin(\r\n    tables: {incident:incident, deployment:deployment},\r\n    on: [\"_time\"],\r\n)\r\n    |> map(fn: (r) => ({ \r\n    _value: \r\n        if r[\"_value_deployment\"] == 0 then \r\n            float(v: 0)\r\n        else\r\n            float(v: r[\"_value_incident\"]) / float(v: r[\"_value_deployment\"]),\r\n    _time: r[\"_time\"]\r\n    }))"
    }
   ]
  },
  { "title": "Mean Time to Restore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Mean Time to Restore",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "incident = from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"incident\")\r\n\r\nrestore = from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"restore\")\r\n\r\njoin(\r\n        tables: {incident:incident, restore:restore},\r\n        on: [\"_value\"],\r\n    )\r\n    |> map(fn: (r) => ({_value: uint(v: r[\"_time_restore\"]) - uint(v: r[\"_time_incident\"])}))\r\n    |> mean()"
    }
   ]
  },
  {
   "title": "Mean Time to Restore",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nincident = from(bucket: \"${bucket}\")\r\n  |> range(start: date.sub(from:${__from:date}, d: ${AggregateInterval}), stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"incident\")\r\n\r\nrestore = from(bucket: \"${bucket}\")\r\n  |> range(start: date.sub(from:${__from:date}, d: ${AggregateInterval}), stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"restore\")\r\n\r\njoin(\r\n        tables: {incident:incident, restore:restore},\r\n        on: [\"_value\"],\r\n    )\r\n    |> map(fn: (r) => ({_value: uint(v: r[\"_time_restore\"]) - uint(v: r[\"_time_incident\"]), _time: r[\"_time_incident\"]}))\r\n    |> aggregateWindow(every: ${AggregateInterval}, fn: mean, createEmpty: false)"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "import \"date\"\r\n from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment\" and r[\"_field\"] == \"id\")\r\n  |> unique(column: \"_value\")\r\n  |> map(fn: (r) => ({deployment:  r[\"_value\"], time: r[\"_time\"]}))\r\n"
    },
    {
     "query": " from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"change\")\r\n  |> map(fn: (r) => ({change:  r[\"_value\"], time: r[\"_time\"]}))"
    },
    {
     "query": " from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"incident\")\r\n  |> map(fn: (r) => ({incident:  r[\"_value\"], time: r[\"_time\"]}))"
    },
    {
     "query": " from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"restore\")\r\n  |> map(fn: (r) => ({restore:  r[\"_value\"], time: r[\"_time\"]}))"
    }
   ]
  },
  {
   "title": "Events",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": " from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment\" and r[\"_field\"] == \"id\")\r\n  |> unique(column: \"_value\")\r\n  |> map(fn: (r) => ({_value: r[\"_value\"]}))\r\n  |> count()\r\n"
    },
    {
     "query": " from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"change\")\r\n  |> map(fn: (r) => ({_value: r[\"_value\"]}))\r\n  |> count()"
    },
    {
     "query": "  from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"incident\")\r\n  |> map(fn: (r) => ({_value: r[\"_value\"], name: \"incident\"}))\r\n  |> count()"
    },
    {
     "query": " from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"restore\")\r\n  |> map(fn: (r) => ({_value: r[\"_value\"]}))\r\n  |> count()"
    }
   ]
  }
 ]
}