name: Test

on:
  pull_request:
    branches:
    - main
  push:

jobs:
  test:
    name: test app
    runs-on: ubuntu@latest
    steps:
      - uses: actions/checkout@v2.4.2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: run tests
        run: npm test
