name: Test

on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get_git_hash:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest   

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
    
      - name: Get Commit Hash
        id: vars
        shell: bash
        run: |
          echo "::set-output name=commit_hash::$(git rev-parse --short "$GITHUB_SHA")"
        
      # Runs a single command using the runners shell
      - name: Output Hash
        run: |
          echo "Hash: ${{ steps.vars.outputs.commit_hash }}"
        
